package drymartini


const SLEEP_CMD_STR string = "sleep"
const EXIT_CMD_STR string = "exit"
const PING_CMD_STR string = "ping"
const JOIN_CMD_STR string = "join"
const WHOAMI_CMD_STR string = "whoami"
const PLB_CMD_STR string = "plb"
const PLD_CMD_STR string = "pld"
const GENPATH_CMD_STR string = "genpath"
const BC_CMD_STR string = "bc"
const FV_CMD_STR string = "fv"
const PLF_CMD_STR string = "plf"
const SEND_CMD_STR string = "send"
const MAKEWARMSWARM_CMD_STR string = "makewarmswarm"
const RUNTESTS_CMD_STR string = "runtests"
const BLOCK_CMD_STR string = "block"
const OPEN_CMD_STR string = "open"
const GETPATH_AND_SEND_CMD_STR string = "getpathandsend"
